const translations = {
  de:{headerTitle:'Direkt buchen',backHome:'Startseite',heroEyebrow:'Ihre Auszeit, durchdacht geplant',heroTitle:'Make room<br>for <em>your time away.</em>',heroCopy:'Wählen Sie Ihre Reisedaten und entdecken Sie das Apartment, das zu Ihrer Auszeit in Villach passt.',searchEyebrow:'Find your BoRa',searchTitle:'Ihre Reise,<br><em>Ihr Rhythmus.</em>',checkIn:'Anreise',checkOut:'Abreise',guests:'Gäste',maxGuests:'max. 4 pro Apartment',searchButton:'Apartments finden',resultsEyebrow:'Ihre Auswahl',resultsTitle:'Drei Orte<br>zum <em>Ankommen.</em>',resultsNote:'Die finale Verfügbarkeit und der Gesamtpreis werden im sicheren Buchungsschritt bestätigt.',howEyebrow:'Von Anfang an klar',step1Title:'Daten wählen',step1Copy:'Sagen Sie uns, wann und mit wie vielen Personen Sie reisen möchten.',step2Title:'Lieblingsort aussuchen',step2Copy:'Vergleichen Sie unsere drei Apartments und wählen Sie Ihren Stil.',step3Title:'Sicher abschließen',step3Copy:'Im nächsten Schritt sehen Sie Preis und Echtzeit-Verfügbarkeit.',summaryEyebrow:'Ihr BoRa Aufenthalt',summaryTitle:'Wählen Sie ein<br><em>Apartment.</em>',summaryNote:'Direkt bei BoRa buchen · 30 % Anzahlung zur Bestätigung',secureButton:'Zum sicheren Buchungsschritt',select:'Auswählen',selected:'Ausgewählt',trip:'Ihre Reisedaten',errorRequired:'Bitte wählen Sie An- und Abreisedatum.',errorDates:'Das Abreisedatum muss nach dem Anreisetag liegen.',perApartment:'pro Apartment',people:'Gäste',apartments:[['First','Gartenblick, ruhige Wärme und liebevoll gestaltete Details.','Gartenblick','Balkon','2 Smart-TVs'],['Green','Naturverbundener Komfort mit Bergblick und viel Raum zum Auftanken.','Bergblick','Balkon','Wasch-Trockner'],['Heaven','Ein heller Ausgangspunkt für Ihren Villach-Moment.','Bergblick','Balkon','Smart-TV']]},
  en:{headerTitle:'Book direct',backHome:'Home',heroEyebrow:'Your stay, thoughtfully planned',heroTitle:'Make room<br>for <em>your time away.</em>',heroCopy:'Choose your travel dates and find the apartment that fits your time away in Villach.',searchEyebrow:'Find your BoRa',searchTitle:'Your trip,<br><em>your rhythm.</em>',checkIn:'Check-in',checkOut:'Check-out',guests:'Guests',maxGuests:'max. 4 per apartment',searchButton:'Find apartments',resultsEyebrow:'Your selection',resultsTitle:'Three places<br>to <em>arrive.</em>',resultsNote:'Final availability and the total price are confirmed in the secure booking step.',howEyebrow:'Clear from the first click',step1Title:'Pick your dates',step1Copy:'Tell us when you are travelling and how many guests are joining.',step2Title:'Choose a favourite',step2Copy:'Compare our three apartments and choose the style that suits you.',step3Title:'Complete securely',step3Copy:'The next step shows your price and real-time availability.',summaryEyebrow:'Your BoRa stay',summaryTitle:'Choose an<br><em>apartment.</em>',summaryNote:'Book directly with BoRa · 30% deposit confirms your stay',secureButton:'Open secure booking',select:'Select',selected:'Selected',trip:'Your trip',errorRequired:'Please choose check-in and check-out dates.',errorDates:'Check-out must be after check-in.',perApartment:'per apartment',people:'guests',apartments:[['First','Garden views, quiet warmth and thoughtfully designed details.','Garden view','Balcony','2 Smart TVs'],['Green','Nature-inspired comfort with mountain views and room to recharge.','Mountain view','Balcony','Washer-dryer'],['Heaven','A bright base for your Villach moment.','Mountain view','Balcony','Smart TV']]},
  hu:{headerTitle:'Közvetlen foglalás',backHome:'Főoldal',heroEyebrow:'A te utazásod, gondosan megtervezve',heroTitle:'Hagyj helyet<br>a <em>kikapcsolódásnak.</em>',heroCopy:'Válaszd ki az utazási dátumokat, majd fedezd fel a Villachban hozzád illő apartmant.',searchEyebrow:'Találd meg a BoRa-dat',searchTitle:'A te utad,<br><em>a te ritmusod.</em>',checkIn:'Érkezés',checkOut:'Távozás',guests:'Vendégek',maxGuests:'max. 4 fő/apartman',searchButton:'Apartmanok keresése',resultsEyebrow:'A te választásod',resultsTitle:'Három hely<br>a <em>megérkezéshez.</em>',resultsNote:'A végső elérhetőséget és teljes árat a biztonságos foglalási lépés erősíti meg.',howEyebrow:'Már az első kattintástól átlátható',step1Title:'Válassz dátumot',step1Copy:'Mondd meg, mikor és hányan utaztok.',step2Title:'Válassz kedvencet',step2Copy:'Hasonlítsd össze a három apartmant, és válaszd ki a neked valót.',step3Title:'Foglalj biztonságosan',step3Copy:'A következő lépésben látod az árat és a valós idejű elérhetőséget.',summaryEyebrow:'A BoRa utazásod',summaryTitle:'Válassz egy<br><em>apartmant.</em>',summaryNote:'Közvetlen foglalás a BoRánál · 30% előleg igazolja vissza',secureButton:'Biztonságos foglalás megnyitása',select:'Kiválasztás',selected:'Kiválasztva',trip:'Utazási adatok',errorRequired:'Kérlek, válaszd ki az érkezés és távozás dátumát.',errorDates:'A távozás napjának későbbinek kell lennie az érkezésnél.',perApartment:'apartmanonként',people:'vendég',apartments:[['First','Kertre néző kilátás, nyugodt melegség és gondosan kialakított részletek.','Kertre néző','Erkély','2 Smart TV'],['Green','Természetközeli kényelem hegyi kilátással és sok térrel a feltöltődéshez.','Hegyi kilátás','Erkély','Mosó-szárítógép'],['Heaven','Világos kiindulópont a te villachi pillanatodhoz.','Hegyi kilátás','Erkély','Smart TV']]},
  it:{headerTitle:'Prenota diretto',backHome:'Home',heroEyebrow:'Il tuo soggiorno, pianificato con cura',heroTitle:'Fai spazio<br>alla <em>tua pausa.</em>',heroCopy:'Scegli le date di viaggio e trova l’appartamento giusto per la tua fuga a Villach.',searchEyebrow:'Trova il tuo BoRa',searchTitle:'Il tuo viaggio,<br><em>il tuo ritmo.</em>',checkIn:'Arrivo',checkOut:'Partenza',guests:'Ospiti',maxGuests:'max. 4 per appartamento',searchButton:'Trova appartamenti',resultsEyebrow:'La tua scelta',resultsTitle:'Tre luoghi<br>in cui <em>arrivare.</em>',resultsNote:'Disponibilità finale e prezzo totale vengono confermati nel passaggio di prenotazione sicuro.',howEyebrow:'Chiaro dal primo click',step1Title:'Scegli le date',step1Copy:'Dicci quando viaggi e quanti ospiti verranno con te.',step2Title:'Scegli il preferito',step2Copy:'Confronta i tre appartamenti e scegli lo stile più adatto a te.',step3Title:'Completa in sicurezza',step3Copy:'Nel prossimo passaggio vedrai il prezzo e la disponibilità in tempo reale.',summaryEyebrow:'Il tuo soggiorno BoRa',summaryTitle:'Scegli un<br><em>appartamento.</em>',summaryNote:'Prenota direttamente con BoRa · acconto del 30% per confermare',secureButton:'Apri prenotazione sicura',select:'Scegli',selected:'Selezionato',trip:'Il tuo viaggio',errorRequired:'Scegli le date di arrivo e partenza.',errorDates:'La partenza deve essere successiva all’arrivo.',perApartment:'per appartamento',people:'ospiti',apartments:[['First','Vista giardino, calore tranquillo e dettagli progettati con cura.','Vista giardino','Balcone','2 Smart TV'],['Green','Comfort ispirato alla natura con vista montagna e spazio per ricaricarsi.','Vista montagna','Balcone','Lavasciuga'],['Heaven','Una base luminosa per il tuo momento a Villach.','Vista montagna','Balcone','Smart TV']]},
  sl:{headerTitle:'Neposredna rezervacija',backHome:'Domov',heroEyebrow:'Vaše bivanje, skrbno načrtovano',heroTitle:'Naredite prostor<br>za <em>svoj oddih.</em>',heroCopy:'Izberite datume potovanja in poiščite apartma, ki ustreza vašemu oddihu v Beljaku.',searchEyebrow:'Najdite svoj BoRa',searchTitle:'Vaše potovanje,<br><em>vaš ritem.</em>',checkIn:'Prihod',checkOut:'Odhod',guests:'Gostje',maxGuests:'največ 4 na apartma',searchButton:'Poiščite apartmaje',resultsEyebrow:'Vaša izbira',resultsTitle:'Trije kraji<br>za <em>prihod.</em>',resultsNote:'Končna razpoložljivost in skupna cena sta potrjeni v varnem koraku rezervacije.',howEyebrow:'Jasno že od prvega klika',step1Title:'Izberite datume',step1Copy:'Povejte nam, kdaj potujete in koliko gostov prihaja.',step2Title:'Izberite favorita',step2Copy:'Primerjajte naše tri apartmaje in izberite slog, ki vam ustreza.',step3Title:'Varno zaključite',step3Copy:'V naslednjem koraku vidite ceno in razpoložljivost v realnem času.',summaryEyebrow:'Vaše bivanje BoRa',summaryTitle:'Izberite<br><em>apartma.</em>',summaryNote:'Rezervirajte neposredno pri BoRa · 30 % predplačilo potrdi bivanje',secureButton:'Odpri varno rezervacijo',select:'Izberi',selected:'Izbrano',trip:'Vaše potovanje',errorRequired:'Izberite datuma prihoda in odhoda.',errorDates:'Datum odhoda mora biti po datumu prihoda.',perApartment:'na apartma',people:'gostje',apartments:[['First','Pogled na vrt, mirna toplina in skrbno oblikovane podrobnosti.','Pogled na vrt','Balkon','2 Smart TV'],['Green','Naravno udobje s pogledom na gore in prostorom za polnjenje energije.','Pogled na gore','Balkon','Pralno-sušilni stroj'],['Heaven','Svetla izhodiščna točka za vaš trenutek v Beljaku.','Pogled na gore','Balkon','Smart TV']]}
};

const images = ['https://boraapartments.at/wp-content/uploads/2025/08/Beige-Simple-Interior-Mood-Board-A4-Landscape5-e1759700725813-1024x672.jpg','https://boraapartments.at/wp-content/uploads/2025/08/Beige-Simple-Interior-Mood-Board-A4-Landscape3-e1764627141977-1024x678.jpg','https://boraapartments.at/wp-content/uploads/2025/08/Beige-Simple-Interior-Mood-Board-A4-Landscape6-e1765837217691-768x505.jpg'];
const languageSelect = document.querySelector('#languageSelect'); const form = document.querySelector('#bookingForm'); const checkIn = document.querySelector('#checkIn'); const checkOut = document.querySelector('#checkOut'); const guests = document.querySelector('#guests'); const results = document.querySelector('#apartments'); const error = document.querySelector('#formError'); const tripLabel = document.querySelector('#tripLabel'); let selectedApartment = null;
const dateFormatter = (code, date) => new Intl.DateTimeFormat(code === 'de' ? 'de-AT' : code, {day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T12:00:00`));
function t(){return translations[languageSelect.value] || translations.de} function updateText(){const dictionary=t();document.documentElement.lang=languageSelect.value;document.querySelectorAll('[data-t]').forEach((node)=>node.textContent=dictionary[node.dataset.t]||node.textContent);document.querySelectorAll('[data-html]').forEach((node)=>node.innerHTML=dictionary[node.dataset.html]||node.innerHTML);document.title=`${dictionary.headerTitle} — BoRa Apartments`;renderApartments();updateSummary();localStorage.setItem('bora-language',languageSelect.value)}
function renderApartments(){
  const dictionary = t();
  results.innerHTML = dictionary.apartments.map((apartment, index) => `<article class="apartment ${selectedApartment === index ? 'is-selected' : ''}"><div class="apartment-image"><img src="${images[index]}" alt="BoRa Apartment ${apartment[0]}" /><span class="apartment-index">0${index + 1}</span></div><div class="apartment-content"><div><h3>Apartment <em>${apartment[0]}</em></h3><p>${apartment[1]}</p></div><div class="tags">${apartment.slice(2).map((tag) => `<span>${tag}</span>`).join('')}</div></div><button class="select-apartment" type="button" data-index="${index}">${selectedApartment === index ? dictionary.selected : dictionary.select}<span>→</span></button></article>`).join('');
  document.querySelectorAll('.select-apartment').forEach((button) => {
    button.addEventListener('click', () => {
      selectedApartment = Number(button.dataset.index);
      renderApartments();
      updateSummary();
      document.querySelector('#summary').scrollIntoView({ behavior: 'smooth', block: 'center' });
    });
  });
}
function updateSummary(){const dictionary=t();const chosen=selectedApartment===null?null:dictionary.apartments[selectedApartment][0];document.querySelector('#summaryApartment').innerHTML=chosen?`Apartment<br><em>${chosen}.</em>`:dictionary.summaryTitle;const dates=checkIn.value&&checkOut.value?`${dateFormatter(languageSelect.value,checkIn.value)} — ${dateFormatter(languageSelect.value,checkOut.value)}`:'—';document.querySelector('#summaryDates').textContent=dates;document.querySelector('#summaryGuests').textContent=guests.value==='1'?`1 ${dictionary.people}`:`${guests.value} ${dictionary.people}`;tripLabel.textContent=checkIn.value&&checkOut.value?`${dictionary.trip}: ${dates} · ${guests.value} ${dictionary.people}`:''}
function setMinimumDates(){const today=new Date();today.setHours(0,0,0,0);const min=today.toISOString().split('T')[0];checkIn.min=min;checkOut.min=min} function validate(){if(!checkIn.value||!checkOut.value){error.textContent=t().errorRequired;return false}if(checkOut.value<=checkIn.value){error.textContent=t().errorDates;return false}error.textContent='';return true}
form.addEventListener('submit',(event)=>{event.preventDefault();if(validate()){updateSummary();document.querySelector('#results').scrollIntoView({behavior:'smooth',block:'start'})}});[checkIn,checkOut,guests].forEach(input=>input.addEventListener('change',()=>{if(checkIn.value)checkOut.min=checkIn.value;updateSummary()}));languageSelect.value=localStorage.getItem('bora-language')||'de';setMinimumDates();updateText();languageSelect.addEventListener('change',updateText);
