const observer = new IntersectionObserver((entries) => {
  entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } });
}, { threshold: 0.14 });
document.querySelectorAll('.reveal').forEach((item) => observer.observe(item));

const glow = document.querySelector('.cursor-glow');
window.addEventListener('pointermove', (event) => { glow.style.left = `${event.clientX}px`; glow.style.top = `${event.clientY}px`; });

const menu = document.querySelector('.menu-toggle');
menu?.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') === 'true'; menu.setAttribute('aria-expanded', String(!open)); });

const languages = {
  de: { title:'BoRa Apartments — Villach, Kärnten', nav:['Apartments','Erleben','Galerie','Anreise'], book:'Jetzt buchen', hero:['A little more','room to breathe.','Ein zeitloser Rückzugsort zwischen Seen, Stadt und den stillen Gipfeln der Alpen.'], intro:['Ein Ort zum Ankommen','Nicht nur<br>übernachten.<br><em>Aufatmen.</em>','BoRa ist Ihr privater Ausgangspunkt für Kärnten. Mit natürlichem Licht, ausgesuchten Details und dem guten Gefühl, genau richtig zu sein.','Die BoRa Welt entdecken'], stats:['individuelle Apartments','Gäste pro Apartment','Momente zum Mitnehmen'], apartments:['Drei Stimmungen.<br><em>Ein Gefühl von Zuhause.</em>','Elegant, warm & mit Liebe zum Detail für 1–4 Personen.','54 m², großzügig, naturverbunden. Für 1–4 Personen.','Moderner Komfort in perfekter Villach-Lage für 1–4 Personen.'], quote:['„Gestaltet für das<br><em>schöne Dazwischen.</em>“','Zwischen dem ersten Kaffee und dem letzten Licht auf den Bergen.'], experience:['Kärnten<br><em>in allen Farben.</em>','Ihr Tagesplan darf ganz spontan sein: See oder Gipfel, Trail oder Therme, Altstadt oder einfach ein langer Morgen am Fenster.','Seen, Trails,<br>Thermen &<br><em>Altstadtflair.</em>','Region erleben'], gallery:'Materialien, Licht und kleine Details, die aus einer Reise einen Lieblingsort machen.', location:['Zentral.<br>Doch ganz bei<br><em>sich.</em>','9500 Villach, Austria<br>Zwischen der Altstadt, den Kärntner Seen und dem ersten Höhenmeter.','Route planen'], booking:['Make room<br>for <em>memories.</em>','Verfügbarkeit prüfen','30 % Anzahlung zur Buchungsbestätigung'], discover:'Entdecken' },
  en: { title:'BoRa Apartments — Villach, Carinthia', nav:['Apartments','Experience','Gallery','Location'], book:'Book now', hero:['A little more','room to breathe.','A timeless retreat between lakes, town and the quiet peaks of the Alps.'], intro:['A place to arrive','Not just<br>a stay.<br><em>A deep breath.</em>','BoRa is your private starting point for Carinthia — filled with natural light, considered details and that feeling of being exactly where you belong.','Discover BoRa'], stats:['individual apartments','guests per apartment','moments to take with you'], apartments:['Three moods.<br><em>One feeling of home.</em>','Elegant, warm and thoughtfully designed for 1–4 guests.','54 m² of generous, nature-inspired space for 1–4 guests.','Modern comfort in a perfect Villach location for 1–4 guests.'], quote:['„Made for the<br><em>beautiful in-between.</em>“','Between the first coffee and the last light on the mountains.'], experience:['Carinthia<br><em>in every colour.</em>','Let your day take shape spontaneously: lake or summit, trail or thermal spa, old town or simply a long morning by the window.','Lakes, trails,<br>thermal spas &<br><em>old-town charm.</em>','Explore the region'], gallery:'Materials, light and little details that turn a trip into a favourite place.', location:['Central.<br>Yet entirely<br><em>your own.</em>','9500 Villach, Austria<br>Between the old town, Carinthian lakes and the first climb.','Plan your route'], booking:['Make room<br>for <em>memories.</em>','Check availability','30% deposit to confirm your booking'], discover:'Discover' },
  hu: { title:'BoRa Apartments — Villach, Karintia', nav:['Apartmanok','Élmények','Galéria','Megközelítés'], book:'Foglalás', hero:['Egy kicsivel több','tér a lélegzethez.','Időtlen menedék tavak, város és az Alpok csendes csúcsai között.'], intro:['Egy hely, ahová jó megérkezni','Ne csak<br>megszállj.<br><em>Lélegezz fel.</em>','A BoRa a saját kiindulópontod Karintiában: természetes fénnyel, gondosan válogatott részletekkel és azzal az érzéssel, hogy pontosan jó helyen vagy.','Fedezd fel a BoRa világát'], stats:['egyedi apartman','vendég apartmanonként','magaddal vitt pillanat'], apartments:['Három hangulat.<br><em>Egy otthonos érzés.</em>','Elegáns, meleg és szeretettel megalkotott tér 1–4 vendégnek.','54 m² tágas, természetközeli tér 1–4 vendégnek.','Modern kényelem tökéletes villachi lokációban, 1–4 vendégnek.'], quote:['„A szépséges<br><em>köztes pillanatokhoz tervezve.</em>“','Az első kávé és a hegyekre hulló utolsó fény között.'], experience:['Karintia<br><em>minden színben.</em>','Alakuljon spontán a napod: tó vagy csúcs, trail vagy termál, óváros vagy egy hosszú reggel az ablak mellett.','Tavak, trailek,<br>termálok &<br><em>óvárosi hangulat.</em>','Fedezd fel a környéket'], gallery:'Anyagok, fények és apró részletek, amelyek egy utazásból kedvenc helyet teremtenek.', location:['Központi.<br>Mégis teljesen<br><em>a tiéd.</em>','9500 Villach, Ausztria<br>Az óváros, a karintiai tavak és az első emelkedő között.','Útvonaltervezés'], booking:['Hagyj helyet<br>az <em>emlékeknek.</em>','Szabad időpontok','Foglalás megerősítéséhez 30% előleg szükséges'], discover:'Felfedezés' },
  it: { title:'BoRa Apartments — Villach, Carinzia', nav:['Appartamenti','Esperienze','Galleria','Come arrivare'], book:'Prenota ora', hero:['Un po’ più','spazio per respirare.','Un rifugio senza tempo tra laghi, città e le vette silenziose delle Alpi.'], intro:['Un luogo in cui arrivare','Non solo<br>un soggiorno.<br><em>Un respiro profondo.</em>','BoRa è il tuo punto di partenza privato per la Carinzia: luce naturale, dettagli scelti con cura e la sensazione di essere esattamente nel posto giusto.','Scopri il mondo BoRa'], stats:['appartamenti unici','ospiti per appartamento','momenti da portare con sé'], apartments:['Tre atmosfere.<br><em>Una sensazione di casa.</em>','Elegante, caldo e curato nei dettagli per 1–4 ospiti.','54 m² di spazio generoso e naturale per 1–4 ospiti.','Comfort moderno in una posizione perfetta a Villach per 1–4 ospiti.'], quote:['„Creato per il<br><em>bellissimo nel mezzo.</em>“','Tra il primo caffè e l’ultima luce sulle montagne.'], experience:['La Carinzia<br><em>in ogni colore.</em>','Lascia che la giornata nasca spontaneamente: lago o vetta, trail o terme, centro storico o una lunga mattina alla finestra.','Laghi, trail,<br>terme &<br><em>fascino del centro.</em>','Scopri la regione'], gallery:'Materiali, luce e piccoli dettagli che trasformano un viaggio in un luogo del cuore.', location:['Centrale.<br>Ma completamente<br><em>tuo.</em>','9500 Villach, Austria<br>Tra il centro storico, i laghi della Carinzia e la prima salita.','Pianifica il percorso'], booking:['Fai spazio<br>ai <em>ricordi.</em>','Verifica la disponibilità','Acconto del 30% per confermare la prenotazione'], discover:'Scopri' },
  sl: { title:'BoRa Apartments — Beljak, Koroška', nav:['Apartmaji','Doživetja','Galerija','Prihod'], book:'Rezervirajte', hero:['Malo več','prostora za dih.','Brezčasen umik med jezeri, mestom in tihimi vrhovi Alp.'], intro:['Kraj za prihod','Ne samo<br>prenočitev.<br><em>Globok vdih.</em>','BoRa je vaše zasebno izhodišče za Koroško — z naravno svetlobo, premišljenimi detajli in občutkom, da ste točno tam, kamor sodite.','Odkrijte svet BoRa'], stats:['edinstveni apartmaji','gostje na apartma','trenutki za s seboj'], apartments:['Tri razpoloženja.<br><em>En občutek doma.</em>','Eleganten, topel in skrbno zasnovan za 1–4 goste.','54 m² prostornega, naravno navdihnjenega prostora za 1–4 goste.','Sodobno udobje na odlični lokaciji v Beljaku za 1–4 goste.'], quote:['„Ustvarjeno za<br><em>lepo vmes.</em>“','Med prvo kavo in zadnjo svetlobo na gorah.'], experience:['Koroška<br><em>v vseh barvah.</em>','Naj se dan razvije spontano: jezero ali vrh, trail ali terme, staro mestno jedro ali dolgo jutro ob oknu.','Jezera, poti,<br>terme in<br><em>čar starega mesta.</em>','Raziščite regijo'], gallery:'Materiali, svetloba in drobni detajli, ki potovanje spremenijo v najljubši kraj.', location:['V središču.<br>A povsem<br><em>po vaše.</em>','9500 Beljak, Avstrija<br>Med starim mestnim jedrom, koroškimi jezeri in prvim vzponom.','Načrtujte pot'], booking:['Naredite prostor<br>za <em>spomine.</em>','Preverite razpoložljivost','30 % predplačilo za potrditev rezervacije'], discover:'Odkrijte' }
};

const villachContent = {
  de:{eyebrow:'Villach, im Fokus',title:'Zwischen Fluss,<br>Stadt <em>& Gipfeln.</em>',copy:'Villach verbindet die Leichtigkeit einer südlichen Stadt mit dem stillen Rhythmus der Alpen. Ein Morgen an der Drau, ein Nachmittag am See, ein Abend im Licht der Altstadt.',link:'Villach entdecken',captions:['Drau & Altstadt','Stadtspaziergang','Abendlicht']},
  en:{eyebrow:'Villach, in focus',title:'Between river,<br>town <em>& peaks.</em>',copy:'Villach blends the ease of a southern town with the quiet rhythm of the Alps. A morning by the Drau, an afternoon at the lake, an evening in the old town’s glow.',link:'Discover Villach',captions:['Drau & old town','A walk through town','Evening light']},
  hu:{eyebrow:'Villach fókuszban',title:'Folyó, város<br><em>& hegycsúcsok között.</em>',copy:'Villach egy déli város könnyedségét ötvözi az Alpok csendes ritmusával. Reggel a Dráva partján, délután a tónál, este az óváros fényeiben.',link:'Fedezd fel Villachot',captions:['Dráva & óváros','Városi séta','Esti fények']},
  it:{eyebrow:'Villach, in primo piano',title:'Tra fiume,<br>città <em>& vette.</em>',copy:'Villach unisce la leggerezza di una città del sud al ritmo quieto delle Alpi. Una mattina sulla Drau, un pomeriggio al lago, una sera nella luce del centro storico.',link:'Scopri Villach',captions:['Drau e centro storico','Passeggiata in città','Luce della sera']},
  sl:{eyebrow:'Beljak v ospredju',title:'Med reko,<br>mestom <em>in vrhovi.</em>',copy:'Beljak združuje lahkotnost južnega mesta s tihim ritmom Alp. Jutro ob Dravi, popoldne ob jezeru, večer v svetlobi starega mestnega jedra.',link:'Odkrijte Beljak',captions:['Drava in staro mesto','Sprehod po mestu','Večerna svetloba']}
};

const text = (selector, value, html = false) => document.querySelectorAll(selector).forEach((node) => { node[html ? 'innerHTML' : 'textContent'] = value; });
const select = document.querySelector('#languageSelect');
function applyLanguage(code) {
  const t = languages[code] || languages.de;
  const villach = villachContent[code] || villachContent.de;
  document.documentElement.lang = code;
  document.title = t.title;
  text('.desktop-nav a:nth-child(1)', t.nav[0]); text('.desktop-nav a:nth-child(2)', t.nav[1]); text('.desktop-nav a:nth-child(3)', t.nav[2]); text('.desktop-nav a:nth-child(4)', t.nav[3]);
  text('.header-book', `${t.book} ↗`); text('.hero h1 .line:first-child', t.hero[0]); text('.hero h1 em.line', t.hero[1]); text('.hero-bottom p', t.hero[2]);
  text('.intro > .eyebrow', t.intro[0]); text('.intro h2', t.intro[1], true); text('.intro-copy p', t.intro[2]); text('.intro-copy .text-link', `${t.intro[3]} →`);
  text('.feature-strip div:nth-child(1) span', t.stats[0]); text('.feature-strip div:nth-child(2) span', t.stats[1]); text('.feature-strip div:nth-child(3) span', t.stats[2]);
  text('.section-title h2', t.apartments[0], true); text('.card-first .card-meta div p', t.apartments[1]); text('.card-green .card-meta div p', t.apartments[2]); text('.card-heaven .card-meta div p', t.apartments[3]); text('.view-circle', `${t.discover} ↗`);
  text('.quote-inner blockquote', t.quote[0], true); text('.quote-inner > p:last-child', t.quote[1]);
  text('.experience-top h2', t.experience[0], true); text('.experience-top > p', t.experience[1]); text('.experience-copy h3', t.experience[2], true); text('.experience-copy .text-link', `${t.experience[3]} →`);
  text('.villach-copy-block .eyebrow', villach.eyebrow); text('.villach-title', villach.title, true); text('.villach-copy', villach.copy); text('.villach-link > span', villach.link); text('.villach-caption-1', `01 — ${villach.captions[0]}`); text('.villach-caption-2', `02 — ${villach.captions[1]}`); text('.villach-caption-3', `03 — ${villach.captions[2]}`);
  text('.gallery-head > p:last-child', t.gallery); text('.location-copy h2', t.location[0], true); text('.location-copy > p:not(.eyebrow)', t.location[1], true); text('.location-copy .text-link', `${t.location[2]} ↗`);
  text('.booking h2', t.booking[0], true); text('.button-light', `${t.booking[1]} ↗`); text('.booking-note', t.booking[2]);
  localStorage.setItem('bora-language', code); select.value = code;
}
applyLanguage(localStorage.getItem('bora-language') || 'de');
select.addEventListener('change', (event) => applyLanguage(event.target.value));
